Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,42 +1,36 @@
-stages:
-  - build
-  - test
-  - deploy
-
-variables:
-  MOD_ID: "creature-mod"
-  JDK: "21"
-
 build-job:
   stage: build
-  image: gradle:jdk${JDK}
+  image: gradle:jdk21
   script:
+    - chmod +x ./gradlew
     - ./gradlew properties
-    - export MOD_VERSION=$(grep "^mod_version=" gradle.properties | cut -d "=" -f2-)
-    - export MINECRAFT_VERSION=$(grep "^minecraft_version=" gradle.properties | cut -d "=" -f2-)
-    - pwd
-    - ls -l
-    - echo "MOD_VERSION=${MOD_VERSION}" > build.env
-    - echo "MINECRAFT_VERSION=${MINECRAFT_VERSION}" >> build.env
-    - ls -l build.env
-    - cat build.env
+    - export MOD_VERSION=$(grep "^mod_version=" gradle.properties | cut -d "=" -f2-) || echo "MOD_VERSION not found"
+    - export MINECRAFT_VERSION=$(grep "^minecraft_version=" gradle.properties | cut -d "=" -f2-) || echo "MINECRAFT_VERSION not found"
+    
+    # Create build.env if versions are available
+    - if [ -n "$MOD_VERSION" ] && [ -n "$MINECRAFT_VERSION" ]; then
+        echo "Creating build.env..."
+        echo "MOD_VERSION=${MOD_VERSION}" > build.env
+        echo "MINECRAFT_VERSION=${MINECRAFT_VERSION}" >> build.env
+      fi
+    
     - ./gradlew build
   artifacts:
-    reports:
-      dotenv: build.env
     paths:
       - build/libs/*.jar
     expire_in: 1 month
-
+    
 test-job:
   stage: test
-  image: gradle:jdk${JDK}
+  image: gradle:jdk21
   script:
     - ./gradlew test
+  dependencies:
+    - build-job
 
 deploy-job:
   stage: deploy
-  image: gradle:jdk${JDK}
+  image: gradle:jdk21
   script:
     - mkdir -p mods
     - cp build/libs/*.jar mods/
